repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: docs/CHANGELOG.md
      - id: mixed-line-ending

  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.3
    hooks:
      - id: conventional-commits
