#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Example of dotfiles documentation
##?
#?? 1.0.0
##?
##? Usage:
##?   documentation <environment> <arg1> [--fields=<fields>] [--country=<country>] [-vV]
##?   documentation command [<file>...]
##?   documentation <another_command>
##?
##? Arguments:
##?   environment      Description of environment
##?   arg1             Description of arg1
##?   fields           Description of fields
##?   country          Description of country
##?   another_command  Description of another_command
##?
##? Options:
##?   -c, --country=<country>  Country [default: CT]
##?   -f, --fields=<fields>    Fields to be shown
##?   -v                       Show response header/body
##?   -V                       Show request and response header/body
##?
docs::eval "$@"

echo "file: ${_}"
echo "[file]: ${file[@]}"
echo "another_command: ${another_command}"
echo "environment: ${environment}"
echo "arg1: ${arg1}"
echo "fields: ${fields}"
echo "country: ${country}"
echo "v: ${_v}"
echo "V: ${_V}"
