#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Generates a random password
#?? 1.0.0
##?
##? Usage:
##?   password_gen [--length=<length>][--no-symbols][--stdout]
##?
##? Options:
##?   -l, --length=<length>  Length of the password [default: 30]
##?   -s, --no-symbols       Do not use symbols (!@#$%^&*) in the passwords
##?   -o, --stdout           Echo the passwork in stdout
docs::eval "$@"

characters="A-Za-z0-9"
[[ "${no_symbols}" != "true" ]] && characters=${characters}'!@#$%^&*'

password=$(head /dev/urandom | LC_ALL=C tr -dc ${characters} | head -c ${length})

if [[ "${stdout}" == "true" ]]; then
  echo ${password}
else
  echo ${password} | pbcopy
  osascript -e 'display notification "'"${password}"'" with title "Password copied to the clipboard"'
fi
