#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show sensitive value
#?? 1.0.0
##?
##? Usage:
##?   sensitive <var_name>
##?
docs::eval "$@"


echo "\
$(gum style --foreground 3 ${var_name})=\
$(gum style --foreground 71 ${!var_name:0:4})\
$(gum style --foreground 8 "***")\
$(gum style --foreground 71 ${!var_name: -4})"
