#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? ssh key tool
##?
##? Dependencies docpars:
##?  $ brew install denisidoro/tools/docpars
##?
##? Usage:
##?     ssh-keys create [--keyname=<keyname>]
##?     ssh-keys public --keyname=<keyname>
##?
##? Arguments:
##?   crete   Crates a ssh keypair
##?   public  Extracts the PULIC key from the give private key
##?
##? Options:
##?   -k, --keyname=<keyname>  SSH key name [default: id_rsa]
##?
docs::eval "$@"

if ${create}; then
  ssh-keygen -t rsa -b 4096 -m pem -f ${keyname}
elif ${public}; then
  if [[ ! -f ${keyname} ]]; then
    echo "Error: ${keyname} does not exists"
    exit 1
  fi
  ssh-keygen -f ${keyname} -y 
fi
