#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show the meteo in a city
#?? 1.0.0
##?
##? Usage:
##?   weather <city> [--detail]
##?
##? Options:
##?   -d, --detail  Detailed view

docs::eval "$@"

if [ "$detail" == "true" ]; then
  curl -4 http://wttr.in/${city}?format=v2
else
  curl -4 http://wttr.in/${city}
fi
