#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show branches age (author date) in current git repo
##? Use -r for remote branches
##?
#?? 1.0.0
##?
##? Usage:
##?   branchAge [-r]
docs::eval "$@"

remote=${1:-""}

git branch ${remote} --sort=-authordate --format '%(authordate:iso) %(align:left,25)%(refname:short)%(end) %(subject)'
