#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Git branches management
##?
#?? 1.0.0
##?
##? Usage:
##?   branch age [--remote]
##?   branch old-age [--remote]
##?
##? Options:
##?   -r, --remote   Remote branches only
##?
docs::eval "$@"

if [ "${old_age}" == "true" ]; then
  remote_arg=""
  [[ "${remote}" == "true" ]] && remote_arg="--remote"
  # Show branches age (author date) in current git repo
  git branch ${remote_arg} --sort=-authordate --format '%(authordate:iso) %(align:left,25)%(refname:short)%(end) %(subject)'
fi
