#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Count files recursives in the current direcory disgregated per subdirectory
#?? 1.0.0
##?
##? Usage:
##?   filecountd [<folder>]
docs::eval "$@"

if [ $# -lt 1 ]; then
    folder=$(pwd)
else
    folder=$(realpath $1)
fi

ls -d ${folder}/*/ | xargs -I _ sh -c "find \"_\" -type f | wc -l | xargs echo \"_\""
