#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Count files recursives in the current direcory
#?? 1.0.0
##?
##? Usage:
##?   filecount [<folder>]
docs::eval "$@"

if [ $# -lt 1 ]; then
    folder=$(pwd)
else
    folder=$(realpath $1)
fi

echo ${folder}

find ${folder} -type f -print | wc -l
