#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Get AWS logs
##?
#?? 1.0.0
##?
##? Usage:
##?   logs get [--log_group=<log_group>][--log_stream=<log_stream>]
##?   logs delete --log_group=<log_group>
##?
##? Options:
##?   -g, --log_group=<log_group>    CloudWatch log group
##?   -s, --log_stream=<log_stream>  CloudWatch los stream
##?
docs::eval "$@"

if [ "${get}" == "true" ]; then
  [[ "${log_group}" == "" ]] && log_group=$(aws logs describe-log-groups | jq -r '.logGroups[].logGroupName' | gum choose --header "Log group...")
  [[ "${log_stream}" == "" ]] && log_stream=$(aws logs describe-log-streams --log-group-name ${log_group} --order-by LastEventTime --descending | jq -r '.logStreams[].logStreamName' | gum choose --header "Log stream...")
  aws logs get-log-events --log-group-name ${log_group} --log-stream-name ${log_stream} | jq -r '.events[].message | gsub("\n"; "")'
fi

if [ "${delete}" == "true" ]; then
  aws logs delete-log-group --log-group-name ${log_group}
fi
