#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Get AWS resources by tag
##?
#?? 1.0.0
##?
##? Usage:
##?   resources_by_tag --key=<key> --values=<values>
##?
##? Options:
##?   -k, --key=<key>        Key to be used as filter
##?   -v, --values=<values>  Comma-separated list of values to filter
##?
docs::eval "$@"

if [ -z AWS_DEFAULT_REGION ]; then
  AWS_DEFAULT_REGION="eu-west-1"
fi

aws resourcegroupstaggingapi get-resources --region ${AWS_DEFAULT_REGION} --tag-filters Key=${key},Values=${values}
