#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Get AWS S3
##?
#?? 1.0.0
##?
##? Usage:
##?   s3 empty --bucket=<bucket>
##?
##? Options:
##?   -b, --bucket=<bucket>    S3 bucket
##?
docs::eval "$@"

log::note "Empting bucket ${bucket}"
versions=$(aws s3api list-object-versions --bucket ${bucket})

num_versions=$(jq '.Versions | length' <<<${versions})
if [ ${num_versions}  -gt 0 ]; then
  objects=$(jq '{Objects: [.Versions[] | {Key:.Key, VersionId : .VersionId}], Quiet: false}' <<<${versions})
  aws s3api delete-objects --bucket ${bucket} --delete "${objects}"
else
  log::warning "Bucket ${bucket} is already empty"
fi
