#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? AWS S3 operations
##?
#?? 1.0.0
##?
##? Usage:
##?   s3 lsb [--output=<output>]
##?   s3 ls [--bucket=<bucket>][--output=<output>]
##?
##? Options:
##?   -b, --bucket=<bucket>    AWS S3 bucket
##?   -o, --output=<output>    Output format (json or table) [default:table]
##?
docs::eval "$@"

if [ "${lsb}" == "true" ]; then
  buckets=$(aws s3api list-buckets)

  if [[ "${output}" == "json" ]]; then
    jq . <<<${buckets}
  else
    jq -r '.Buckets[] | [.Name, .CreationDate] | @csv' <<<${buckets} | gum table --print --columns "Name,Creation date"
  fi
fi

if [ "${ls}" == "true" ]; then
  [[ "${bucket}" == "" ]] && bucket=$(aws s3api list-buckets | jq -r '.Buckets[].Name' | gum choose --header "Bucket...")

  content=$(aws s3api list-objects --bucket ${bucket})

  if [[ "${output}" == "json" ]]; then
    jq . <<<${content}
  else
    jq -r '.Contents[] | [.Key, .Size, .LastModified] | @csv' <<<${content} | gum table --print --columns "Object,Size,Last modified"
  fi
fi
