#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Get AWS secrets from Secrets Manager
##?
#?? 1.0.0
##?
##? Usage:
##?   secrets get [--filter=<filter>][--output=<output>]
##?
##? Options:
##?   -a, --filter=<filter>   Filter string for the secret
##?   -o, --output=<output>   Output format (full, value, plain)[default: value]
##?
docs::eval "$@"

if [ "${get}" == "true" ]; then

  secret_list=$(aws secretsmanager list-secrets | jq -r '.SecretList[].ARN')
  secrets=(${secret_list})
  height=$((${#secrets[@]} + 4)) # 4 = Fitler headers & footers
  arn=$(echo ${secrets[@]} | tr ' ' '\n' | gum filter --select-if-one --limit=1 --height=${height} --header "Secrets (${#secrets[@]})" --value "${filter}")

  if [[ "${output}" == "value" ]]; then
    log::header "${arn}"
  fi
  secret_value=$(aws secretsmanager get-secret-value --secret-id "${arn}")

  if [[ "${output}" == "value" || "${output}" == "plain" ]]; then
    jq -r '.SecretString' <<<${secret_value} | jq .
  elif [[ "${output}" == "full" ]]; then
    jq . <<<${secret_value}
  else
    log::error "Unknown output option '${output}'"
    exit 1
  fi
fi
