#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Get AWS secrets from Secrets Manager
##?
#?? 1.0.0
##?
##? Usage:
##?   logs get [--arn=<arn>][--output=<output>]
##?
##? Options:
##?   -a, --arn=<arn>         Secret ARN
##?   -o, --output=<output>   Output format (all, value)[default: value]
##?
docs::eval "$@"

if [ "${get}" == "true" ]; then
  [[ "${arn}" == "" ]] && arn=$(aws secretsmanager list-secrets | jq -r '.SecretList[].ARN' | gum choose --header "Secret ARN...")

  secret_value=$(aws secretsmanager get-secret-value --secret-id "${arn}")

  if [[ "${output}" == "value" ]]; then
    jq -r '.SecretString' <<<${secret_value}
  elif [[ "${output}" == "all" ]]; then
    jq . <<<${secret_value}
  else
    log::error "Unknown output option '${output}'"
    exit 1
  fi
fi
