#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Describe VPC attributes
##?
#?? 1.0.0
##?
##? Usage:
##?   vpc subnets [--filter=<filter>][--output=<output>]
##?   vpc prefix-list [--filter=<filter>][--output=<output>]
##?
##? Options:
##?   -f, --filter=<filter>  Word to be contained in the filter (subnet, prefix-list)
##?   -o, --output=<output>  Output format (table, json)[default: table]
##?
docs::eval "$@"

if [ "${subnets}" == "true" ]; then
  subnets=$(aws ec2 describe-subnets)

  filtered_subnets=$(jq '.Subnets' <<<"${subnets}")
  if [[ "${filter}" != "" ]]; then
    filtered_subnets=$(jq -r --arg FILTER "${filter}" '
      [ .Subnets[]
        | select((.Tags[] | select(.Key == "Name").Value) | contains($FILTER))
      ]
    ' <<<"${subnets}")
  fi

  if [ "${output}" == "json" ]; then
    jq -r '
      [ .[] | {
          cidr: .CidrBlock,
          name: (.Tags[] | select(.Key == "Name").Value),
          available_ips: .AvailableIpAddressCount
        }
      ]
    ' <<<"${filtered_subnets}"
  else
    jq -r '
      .[]
      | (.CidrBlock | split("/")[1] | tonumber) as $prefix
      | (pow(2; 32 - $prefix) - 5) as $total
      | (if (.AvailableIpAddressCount / $total) < 0.25 then "⚠️  " else "" end) as $warn
      | [
          .CidrBlock,
          (.Tags[] | select(.Key == "Name").Value),
          $warn + (.AvailableIpAddressCount | tostring)
        ]
      | @csv
    ' <<<"${filtered_subnets}" \
      | sort -t ',' -k 2 \
      | gum table --print --columns "CIDR, Name, Available IPs"
  fi
fi

if [ "${prefix_list}" == "true" ]; then
  pl=$(aws ec2 describe-managed-prefix-lists)

  if [ "${output}" == "json" ]; then
    jq -r '.PrefixLists' <<<"${pl}"
  else
    jq -r --arg FILTER "${filter}" '
      .PrefixLists
      | sort_by(.PrefixListName)[]
      | select(.PrefixListName | contains($FILTER))
      | [.PrefixListId, .PrefixListName]
      | @csv
    ' <<<"${pl}" \
      | gum table --print --columns "ID,Name"
  fi
fi
