#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Interact with workspace GIT repositories
##?
#?? 1.0.0
##?
##? Usage:
##?   repos pull
##?   repos pre-commit
##?
##? Arguments:
##?   pull        Pull all git repos
##?   pre-commit  Runs pre-commit install in all git repos
##?
docs::eval "$@"

[[ -z ${WS} ]] && work_dir=$(dirname ${DOTFILES_PATH}) || work_dir=${WS}

for gitdir in `find ${work_dir} -type d \( -path "*/.terraform" -o -path "*/.terragrunt-cache" \) -prune -o -name .git -print`; do
  pushd $(dirname $gitdir) >& /dev/null
  if [ "${pull}" == "true" ]; then
    log::note "Updating $(basename $(dirname $gitdir))"
    git pull
  elif [ "${pre_commit}" == "true" ]; then
    log::note "Installing pre-commit in $(dirname $gitdir)"
    pre-commit install
    for hook_type in $(echo "commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg"); do
      pre-commit install -t ${hook_type} > /dev/null
    done
  fi
  popd >& /dev/null
done
