#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Get password from 1password
#?? 1.0.0
##?
##? Usage:
##?   1password <city>
docs::eval "$@"

eval $(op signin my)

op get item ${1} | jq -r .details.fields[1].value | pbcopy
