#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? outputs all the combinations of elemnts in set1 with elements in set2
##?
##? Source: https://catonmat.net/set-operations-in-unix-shell-simplified
#??
#?? 1.0.0
##?
##? Usage:
##?   cartesian_product <set1> <set2>
docs::eval "$@"

while read a; do while read b; do echo "$a, $b"; done < ${set1}; done < ${set2}
