#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? outputs something if subset is not a subset of set
##? does not output anything if subset is a subset of set
##?
##? Source: https://catonmat.net/set-operations-in-unix-shell-simplified
#??
#?? 1.0.0
##?
##? Usage:
##?   subset <subset> <set1>
docs::eval "$@"

comm -23 <(sort ${subset} | uniq) <(sort ${set1} | uniq) | head -1
