#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Clone a repository in Github in a given folder
##?
#?? 1.0.0
##?
##? Usage:
##?   clone <repository>
##?
##? Arguments:
##?   repository  Repository name within the organization
##?
docs::eval "$@"

# Set GITHUB_ORGANIZATION variable to search in your specific organization
organization=${GITHUB_ORGANIZATION:-abelazo}

if [[ ! -d ${WS}/${repository} ]]; then
  pushd ${WS} >& /dev/null
  git clone git@github.com:${organization}/${repository}
  log::success "${repository} cloned"
  popd >& /dev/null
else
  log::warning "Repository ${repository} already exists"
fi
