#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Search people in Github using gh CLI
##?
#?? 1.0.0
##?
##? Usage:
##?   people
##?
##?
docs::eval "$@"

# Set GITHUB_ORGANIZATION variable to search in your specific organization
organization=${GITHUB_ORGANIZATION:-abelazo}

count=1
page=1
results=$(mktemp)
until [ ${count} -eq 0 ]; do
  page_content=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" '/orgs/'${organization}'/members?page='${page}'&per_page=100')
  echo ${page_content} >> ${results}
  count=$(jq length <<<${page_content})
  ((page++))
done
cat ${results} | jq -s 'add'
rm -f ${results}
