#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Search repos in Github using gh CLI
##?
#?? 1.0.0
##?
##? Usage:
##?   repos list [--name=<name>][--limit=<limit>]
##?
##? Arguments:
##?   list  List repositories of a given organization
##?
##? Options:
##?   -l, --limit=<limit>  Results limit (ignored when name is provided) [default: 100]
##?   -n, --name=<name>    Repository name
##?
docs::eval "$@"

# Set GITHUB_ORGANIZATION variable to search in your specific organization
organization=${GITHUB_ORGANIZATION:-abelazo}

list_repos() {
  if [ -z "${name}" ]; then
    log::note "Showing all repositories"
    gh repo list ${organization} -L ${limit} --no-archived
  else
    results=$(gh search repos --owner=${organization} -L 1000 --match name ${name} --json name | jq -r .[].name)
    log::note "Showing $(echo ${results} | wc -w) repositories"
    echo ${results} | tr " " "\n" | sort | grep --color ${name}
  fi
}

if [ "${list}" == "true" ]; then
  list_repos
  exit 0
fi
