#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Search repos in Github using gh CLI
##?
#?? 1.0.0
##?
##? Usage:
##?   repos list [--name=<name>][--limit=<limit>]
##?   repos teams --name=<name>
##?   repos clone --name=<name>
##?
##? Arguments:
##?   list   List repositories of a given organization
##?   teams  List teams permissions of a repo
##?   clone  Clone one of the repos containing <name>
##?
##? Options:
##?   -l, --limit=<limit>  Results limit (ignored when name is provided) [default: 100]
##?   -n, --name=<name>    Repository name
##?
docs::eval "$@"

# Set GITHUB_ORGANIZATION variable to search in your specific organization
organization=${GITHUB_ORGANIZATION:-abelazo}

list_repos() {
  if [ -z "${name}" ]; then
    log::note "Showing all repositories"
    gh repo list ${organization} -L ${limit} --no-archived
  else
    results=$(gh search repos --owner=${organization} -L 1000 --match name ${name} --json name | jq -r .[].name)
    log::note "Showing $(echo ${results} | wc -w) repositories"
    echo ${results} | tr " " "\n" | sort | grep --color ${name}
  fi
}

if [ "${list}" == "true" ]; then
  list_repos
  exit 0
fi

if [ "${teams}" == "true" ]; then
  log::header "Teams with permissions in ${name}"
  gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${organization}/${name}/teams | jq -r '["Name","Admin", "Maintain", "Push", "Triage", "Pull"], (.[] | [.name, .permissions.admin, .permissions.maintain, .permissions.push, .permissions.triage, .permissions.pull]) | @csv' | gum table --print
  exit 0
fi

if [ "${clone}" == "true" ]; then
  results=$(gh search repos --owner=${organization} -L 1000 --match name ${name} --json name)
  repository=$(jq -r '.[].name' <<<${results} | gum filter --header "Repository")
  [[ repository != "" ]] && git clone git@github.com:${organization}/${repository}
fi
