#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Search teams in Github using gh CLI
##?
#?? 1.0.0
##?
##? Usage:
##?   team list [--depth=<depth>]
##?   team members --team=<team>
##?   team repos --team=<team> [--output=<output>]
##?
##? Arguments:
##?   list     List teams within the organization
##?   members  List members of a given team
##?   repos    List repos of a given team
##?
##? Options:
##?   -d, --depth=<depth>    Max depth in the search (0 means no limit) [default: 0]
##?   -o, --output=<output>  Output format (table|json) [default: table]
##?   -t, --team=<team>      Team name
##?
docs::eval "$@"

# Set GITHUB_ORGANIZATION variable to search in your specific organization
organization=${GITHUB_ORGANIZATION:-abelazo}

process_node() {
  local parent_name="${1}"
  local current_level=${2}
  local depth=${3}

  if [[ ${depth} -ne 0 ]]; then
    (( current_level > depth )) && return
  fi

  if [[ "${parent_name}" == "null" ]]; then
    childs=$(jq -r '[.[] | select(.parent == null)]' <<<${teams})
  else
    spaces=$(( 2 * (current_level-1) ))
    printf "%${spaces}s%s\n" '' "$parent_name"
    childs=$(jq -r '[.[] | select(.parent.name == "'"${parent_name}"'")]' <<<${teams})
  fi

  if [[ $(jq length <<<${childs}) -eq 0 ]]; then
    return
  else
    while read -r child; do
      process_node "${child}" $((current_level + 1)) ${depth}
    done < <(jq -r '.[].name' <<<${childs})
  fi
}

if [[ "${list}" == "true" ]]; then
  teams=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" '/orgs/'${organization}'/teams' --paginate)
  process_node "null" 0 ${depth}
fi

if [[ "${members}" == "true" ]]; then
  team_slug=$(echo ${team} | sed 's/--/-/g')
  members=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/orgs/${organization}/teams/${team_slug}/members" --paginate)

  if [[ ${?} -eq 0 ]]; then
    num_members=$(jq -r .[].login <<<${members} | wc -l | xargs)
    log::note "# ${team} (${num_members})"
    jq -r .[].login <<<${members} | sort
  fi
fi

if [[ "${repos}" == "true" ]]; then
  team_slug=$(echo ${team} | sed 's/--/-/g')
  log::header "Repositories with permission for ${team}"
  result=$(gh api --paginate -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/${organization}/teams/${team_slug}/repos)
  if [[ "${output}" == "table" ]]; then
    echo ${result} | jq -r '["Name","Admin", "Maintain", "Push", "Triage", "Pull"], (.[] | [.name, .permissions.admin, .permissions.maintain, .permissions.push, .permissions.triage, .permissions.pull]) | @csv' | gum table --print
  else
    echo ${result} | jq '.[] | {"name": .name, "admin": .permissions.admin, "maintain": .permissions.maintain, "push": .permissions.push, "triage": .permissions.triage, "pull": .permissions.pull}'
  fi
fi
