#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

basepath=$(dirname $0)

##?
##? Search users in Github using gh CLI
##?
#?? 1.0.0
##?
##? Usage:
##?   user list
##?   user contributions --user=<user> --search=<search>
##?
##? Arguments:
##?   list           List all users of a Github organization
##?   contributions  Find contributions of the given user
##?
##? Options:
##?   -s, --seach=<search>  Search string to filter contributions
##?   -u, --user=<user>     Github user name
##?   -v, --verbose         Verbose output
##?
docs::eval "$@"

# Set GITHUB_ORGANIZATION variable to search in your specific organization
organization=${GITHUB_ORGANIZATION:-abelazo}

if [[ "${list}" == "true" ]]; then
  gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/orgs/${organization}/members" --paginate | jq -r .[].login | sort
fi

if [[ "${contributions}" == "true" ]]; then
  gh api search/commits -X GET --raw-field q="\"${search}\" org:${GITHUB_ORGANIZATION} author:${user}" --jq '.items[] | {repo: .repository.full_name, author: .author.login, date: .commit.author.date}'
fi
