#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

basepath=$(dirname $0)

##?
##? Github workflows management
##?
#?? 1.0.0
##?
##? Usage:
##?   workflow run --workflow=<workflow> [--input=<input>...][--watch]
##?
##? Arguments:
##?   run   Run workflow
##?
##? Options:
##?   -i, --input=<input>        Workflow input parameter (key=value format)
##?   -f, --workflow=<workflow>  Workflow name [default: workflow.yaml]
##?   -w, --watch
##?
docs::eval "$@"

workflow_inputs=""
for i in "${input[@]}"; do
    workflow_inputs+=" --raw-field ${i}"
done

gh workflow run ${workflow} ${workflow_inputs}

gum spin --title "Waiting for workflow ${workflow}..." -- bash -c "source ${basepath}/utils/functions.sh && wait_for_workflow ${workflow}"

run_id=$(gh run list --workflow ${workflow} --json databaseId -q '.[0].databaseId')
if [[ "${watch}" == "true" ]]; then
  gh run watch ${run_id}
else
  gh run view ${run_id}
fi
