#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Sets system volume
#?? 1.0.0
##?
##? Usage:
##?   volume <percentage>
docs::eval "$@"

osascript -e 'set volume output volume "'${percentage}'"'
