#!/usr/bin/env node

// prepare-commit-msg hook used by [git mob](https://github.com/findmypast-oss/git-mob)
// This hook can be linked in any local repository
// for repo in `find $HOME/ws/work -name .git`; do pushd $(dirname $repo)/.git/hooks >& /dev/null; ln -s $DOTFILES_PATH/scripts/git/hooks/prepare-commit-msg; popd >& /dev/null; done

let exec = require('child_process').exec,
    fs = require('fs');

const commitMessage = process.argv[2];
// expect .git/COMMIT_EDITMSG
if(/COMMIT_EDITMSG/g.test(commitMessage)){
    let contents = "";
    exec("git mob-print",
      function (err, stdout) {
        if(err) {
            process.exit(0);
        }

        // opens .git/COMMIT_EDITMSG
        contents = fs.readFileSync(commitMessage);

        if(contents.indexOf(stdout.trim()) !== -1) {
            process.exit(0);
        }

        // Show in console any co-authors that were added
        if(stdout.trim().length) {
            const cyan = '\x1b[36m%s\x1b[0m';
            console.log(cyan, stdout.trim());
        }

        const commentPos = contents.indexOf('# ');
        const gitMessage = contents.slice(0, commentPos);
        const gitComments = contents.slice(commentPos)

        fs.writeFileSync(commitMessage, gitMessage + stdout + gitComments);
        process.exit(0);
    });
}
