#
# Taps
tap "beeftornado/rmtree"
tap "denisidoro/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
#
# brew formulae
#
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "bat"
brew "coreutils"
brew "docpars"
brew "dos2unix"
brew "emacs"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "hstr"
brew "htop"
brew "httpie"
brew "ispell"
brew "jq"
brew "pstree"
brew "tree"
brew "watch"
brew "wget"
brew "ykman"           # Yubikey manager
brew "yq"
brew "yubico-piv-tool" # Yubikey PIV module
#
# Cask
#
cask "bitwarden"
cask "deezer"
cask "gpg-suite"
cask "rectangle"
cask "vlc"
cask "xbar"
cask "zoom"
