#
# Taps
tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mike-engel/jwt-cli"
tap "pivotal/tap"
tap "versent/taps"
#
# brew formulae
#
brew "aws-iam-authenticator"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "bat"
brew "coreutils"
brew "ctop"
brew "denisidoro/tools/docpars"
brew "dos2unix"
brew "emacs"
brew "fzf"
brew "git"
brew "git-delta"
brew "git-gui"
brew "gnu-sed"
#brew "gradle"
#brew "gradle-completion"
brew "hstr"
brew "htop"
# brew "httpie" # use pip3 instead
brew "ispell"
brew "jq"
brew "jwt-cli"
brew "kubectl"
brew "kubectx"
brew "kubernetes-cli"
brew "maven"
brew "node"
brew "pstree"
brew "versent/taps/saml2aws"
brew "watch"
brew "wget"
brew "ykman"           # Yubikey manager
brew "yubico-piv-tool" # Yubikey PIV module
#
# Cask
#
# cask "1password-cli" v2.0 is required
cask "meld"
cask "rectangle"
cask "vlc"
#
#
#mas "Amphetamine", id: 937984704
#mas "Dato", id: 1470584107
#mas "Disk Speed Test", id: 425264550
#mas "GarageBand", id: 682658836
#mas "iMovie", id: 408981434
#mas "Keynote", id: 409183694
#mas "Monosnap", id: 540348655
