#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Brew software management
##?
#?? 1.0.0
##?
##? Usage:
##?   brew install [-f][<additional_brew_file>...]
##?   brew upgrade [-y]
##?
##? Commands:
##?   install  Installs all brew formulae present in core and addtional files
##?   upgrade  Updates brew and upgrades all outdated formulae
##?
##? Arguments:
##?   additional_brew_file  Additional Brewfiles to be installed
##?
##? Options:
##?   -f  Forces cleanup brew installation to match given Brewfiles
##?   -y  Upgrades all outdated formulae avoiding asking for information 
##?
docs::eval "$@"

if [ "${install}" == "true" ]; then

  log::header "Installing  homebrew formulae"
  export HOMEBREW_NO_AUTO_UPDATE=0
  core_brewfile=${DOTFILES_PATH}/os/mac/brew/Brewfile
  log::note "Installing core Brewfile: ${core_brewfile}"
  brew bundle --file=${core_brewfile}
  
  if [ ${#additional_brew_file[@]} -gt 0 ]; then
    for candidate_file in "${additional_brew_file[@]}"; do
      brewfile=$(realpath  ${candidate_file})
      if [ -f ${brewfile} ]; then
        log::note "Installing additional Brewfile: ${brewfile}"
        brew bundle --file=${brewfile}
        brew cleanup
      fi
    done
  fi
  
  if [ "${_f}" == "true" ]; then
    log::warning "Force brew bundle cleanup according to the given Brewfiles"  
    union_brewfile=$(mktemp)
    
    cat ${core_brewfile} >> ${union_brewfile}
    if [ ${#additional_brew_file[@]} -gt 0 ]; then
      for candidate_file in "${additional_brew_file[@]}"; do
        brewfile=$(realpath  ${candidate_file})
        if [ -f ${brewfile} ]; then
          cat ${brewfile} >> ${union_brewfile}
        fi
      done
    fi
    log::note "Force cleanup of Brewfile"
    brew bundle --force cleanup --file=${union_brewfile}
    brew cleanup
    rm ${union_brewfile}
  fi
fi

if [ "${upgrade}" == "true" ]; then
  log::header "Upgrading homebrew formulae"
  brew update &> /dev/null
  log::note "Obtaining outdated formulae"
  outdated=$(brew outdated --quiet)

  [[ -z ${outdated} ]] && exit # No additional installation required

  brew outdated --verbose
  if [ "${_y}" == "true" ]; then
    upgrade_confirmation="y"
  else
    echo -n "Do you want to upgrade outdated formulae [y/N]: "
    read input

    input=$([[ -z ${input} ]] && echo "n" || echo ${input})
    upgrade_confirmation=$(echo ${input} | tr '[:upper:]' '[:lower:]')
  fi

  if [ "${upgrade_confirmation}" == "y" ]; then
    log::note "Upgrading outdated formulae"
    brew upgrade
    brew cleanup
  fi
fi
