#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Get password from 1password
#?? 1.0.0
##?
##? Usage:
##?   1password <item> [--otp]
docs::eval "$@"

# It assumes my has been already configured
eval $(op signin my)

if [ "${otp}" = "true" ]; then
  op get totp ${item} | pbcopy
else
  op get item ${item} | jq -r .details.fields[1].value | pbcopy
fi
