#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Get password from 1password
#?? 2.0.0
##?
##? Usage:
##?   1password <item> [--otp]
docs::eval "$@"

# 1password7 authentication method. It assumes "my" has been already configured
# eval $(op signin --account my)
# The combination of 1password 8 + 1password CLI 2.0 supports biometric authentication

if [ "${otp}" = "true" ]; then
   op item get ${item} --field type=otp --format json | jq -r .totp | pbcopy
else
  op item get ${item} --fields label=password --format human-readable | pbcopy
fi
