#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##?
##? Call Backstage API
##?
#?? 1.0.0
##?
##? Usage:
##?   api [--verb=<verb>] <url>
##?
##? Options:
##?   -v, --verb=<verb>  HTTP verb (GET, POST, PUT) [default: GET]
##?
docs::eval "$@"

backstage_base_url=${BACKSTAGE_BASE_URL:-http://localhost:7000}

if [ -z "$JWT_AUTH_TOKEN" ]; then
  log::error "JWT_AUTH_TOKEN environment variable not set"
  exit 1
fi

set -x
http \
  --auth-type bearer \
  --auth ${JWT_AUTH_TOKEN} \
  "${verb}" "${backstage_base_url}/api${url}" \
  "Origin: ${backstage_base_url}" \
  "Accept: */*" \
  "Accept-Language: en-US,en;q=0.9" \
  "Content-Type: application/json" \
  "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:155.0) Gecko/20100101 Firefox/155.0" \
  "DNT: 1" \
  "Connection: keep-alive" \
  "Sec-Fetch-Dest: empty" \
  "Sec-Fetch-Mode: cors" \
  "Sec-Fetch-Site: same-origin" \
  "Sec-GPC: 1" \
  "Priority: u=4" \
  "TE: trailes"
